### ISSUE TITLE
How to run ?

### ISSUE THREAD

**Issue by Xiyou521** [Tviskaron/pogema-baselines#1]
Hello,I want to run your code .Can you tell me the step?Thanks.

**Comment by Tviskaron** [comment]
Hi! Thank you for your interest) First, you need to install dependencies:
```bash
pip3 install -r docker/requirements.txt
```
Then just run ```main.py``` file (optionally specifying configuration). 
I have significantly updated Pogema library, thus probably the current code will not work with the new (1.1.0) version. 
Therefore, if an error occurs, I recommend trying version 1.0. 

I plan to update these baselines for the new version of Pogema, so there will be an update soon, where I will also add detailed running instructions.

**Comment by Xiyou521** [comment]
Thank you very much for your guidance and look forward to your update.

**Comment by Tviskaron** [comment]
I've done with the update and instructions, thus closing the issue.
