### ISSUE TITLE
New issue when running 32X32 and 64X64

### ISSUE THREAD

**Issue by 98luobo** [Tviskaron/pogema-baselines#10]
When I run 32X32 and 64X64, the program is killed by the system. I don't know if you have such a question?

**Comment by Tviskaron** [comment]
I haven’t experienced this specific issue. However, it might be related to insufficient RAM, especially if the problem does not occur with simpler configurations. I recommend monitoring your system’s memory usage during these runs. 

Additionally, it’s worth noting that PyMARL hasn’t been updated for several years and I observed memory leaks on the part of my experiments...

**Comment by 98luobo** [comment]
Yes, I have also observed memory bursting in my experiments. This code base is confusing to me...

**Comment by 98luobo** [comment]
Hi, bor. I found a new way to work around this. Without pydantic, the program works better. Please wait for me to send my modified code to the comments section.

**Comment by 98luobo** [comment]
New ISSUE: Hi, I was wondering how much memory do you actually need to run 32x32 and 64x64 experiments?

**Comment by Tviskaron** [comment]
Indeed, the PyMARL code is a bit outdated. In my opinion, it might not be worthwhile to delve deeply into identifying the specific error, as it's likely attributable to outdated dependencies that haven't been updated in a while.

I'm in the process of rewriting QMIX following the Clean RL paradigm. This update is expected to only address the memory leak issue.

**Comment by Tviskaron** [comment]
> New ISSUE: Hi, I was wondering how much memory do you actually need to run 32x32 and 64x64 experiments?

I've tested it on a server with 256GB of RAM.
