### ISSUE TITLE
visualize

### ISSUE THREAD

**Issue by Xiyou521** [Tviskaron/pogema-baselines#6]
Hello, I ran your code and displayed the results on the terminal and wandb. How can I visualize the environment? I would appreciate it if you could answer.

**Comment by Tviskaron** [comment]
Hi! You can turn on animation rendering using AnimationWrapper (see [example](https://colab.research.google.com/drive/19dSEGTQeM3oVJtVjpC162t1XApmv6APc?usp=sharing) on colab).
