### ISSUE TITLE
Credentials to Asynchronous PPO

### ISSUE THREAD

**Issue by Arseni1919** [Tviskaron/pogema-baselines#8]
What is the paper of Asynchronous PPO that the algorithm is based on?
I cannot find it, unfortunately.

**Comment by Tviskaron** [comment]
I couldn't find any specific paper on Asynchronous PPO. It seems to be a folklore algorithm without a specific reference. However, you may find some information in OpenAI papers, such as OpenAI Five. In this code we used SampleFactory implementation of APPO (https://proceedings.mlr.press/v119/petrenko20a.html)

**Comment by Arseni1919** [comment]
Thanks.
